version: "3.9"

services:

  postgres:

    image: postgres:17

    container_name: painel-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: painel

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:

    build:
      context: .
      dockerfile: Dockerfile

    container_name: painel-app

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/painel
      JWT_SECRET: 123456789
      NODE_ENV: production
      TZ: America/Fortaleza

    volumes:
      - ./videos:/app/videos

volumes:
  postgres_data: